# this is the client workflow that will create a pull request
# on client push to a given branch

name: Create pull-reqeust on new forecast

on: 
  push:
    branches: [ ptest ]
    
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      # this first step performs the checkout of the ptest branch
      - name: checkout repo
        uses: actions/checkout@v3 
        
      # let's dump some details
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
         format: 'json'
        
      - name: Dump pusher and commit info
        run: |
          echo '${{ toJSON(github.event.pusher) }}'
          echo '${{ toJSON(github.event.head_commit) }}'
          echo '${{ toJSON(steps.files.outputs) }}'
      
      
      # then a pull-request is created for the main branch  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update forecast
          title: Update Forecast
          body: new forecast submitted
          branch: main
      
